# Generated by Django 3.2.20 on 2023-07-28 23:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('wagtailcore', '0083_workflowcontenttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('blog', '0002_blogindexpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogIndexPage',
            new_name='HomePage',
        ),
    ]
